connect postgresql and import db

In [11]:
import pandas as pd
from sqlalchemy import create_engine
from dotenv import dotenv_values

config = dotenv_values()

url = f"postgresql://{config['POSTGRES_USER']}:{config['POSTGRES_PASS']}@{config['POSTGRES_HOST']}:{config['POSTGRES_PORT']}/{config['POSTGRES_DB']}"
engine = create_engine(url)

query = """
SELECT *
FROM aero_insights.prep_final
ORDER BY date, airport_code
"""

df = pd.read_sql(query, engine)
df.shape

(140, 24)

In [12]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   airport_code           140 non-null    str
 1   date                   140 non-null    object
 2   flights_out            140 non-null    int64
 3   flights_in             140 non-null    int64
 4   total_flights          140 non-null    int64
 5   origin_cancelled_rate  140 non-null    float64
 6   dest_cancelled_rate    140 non-null    float64
 7   total_cancelled_num    140 non-null    int64
 8   total_diverted_num     140 non-null    int64
 9   origin_diverted_rate   140 non-null    float64
 10  dest_diverted_rate     140 non-null    float64
 11  avg_dep_delay          140 non-null    timedelta64[us]
 12  avg_arr_delay          140 non-null    timedelta64[us]
 13  station_id             140 non-null    int64
 14  avg_temp_c             140 non-null    float64
 15  min_temp_c             140 non-null    float64
 16  max_temp_c             140 non-null    float64
 17  precipitation_mm       140 non-null    float64
 18  max_snow_mm            112 non-null    float64
 19  avg_wind_direction     0 non-null      object
 20  avg_wind_speed         140 non-null    float64
 21  avg_peakgust           0 non-null      object
 22  avg_pressure_hpa       140 non-null    float64
 23  sun_minutes            0 non-null      object
dtypes: float64(11), int64(6), object(4), str(1), timedelta64[us](2)
memory usage: 26.4+ KB

airport_code               0
date                       0
flights_out                0
flights_in                 0
total_flights              0
origin_cancelled_rate      0
dest_cancelled_rate        0
total_cancelled_num        0
total_diverted_num         0
origin_diverted_rate       0
dest_diverted_rate         0
avg_dep_delay              0
avg_arr_delay              0
station_id                 0
avg_temp_c                 0
min_temp_c                 0
max_temp_c                 0
precipitation_mm           0
max_snow_mm               28
avg_wind_direction       140
avg_wind_speed             0
avg_peakgust             140
avg_pressure_hpa           0
sun_minutes              140
dtype: int64

In [ ]:
# stats for flights

df.groupby("airport_code")[[
    "total_flights",
    "total_cancelled_num",
    "origin_cancelled_rate",
    "dest_cancelled_rate",
    "avg_dep_delay",
    "avg_arr_delay"
]].agg(["mean", "std", "min", "max", "sum"]).T

airport_code                                   ATL                       BOS  \
total_flights         mean              112.357143                718.571429
                      std                 9.153887                 88.777053
                      min                       89                       508
                      max                      122                       810
                      sum                     3146                     20120
total_cancelled_num   mean                     3.0                 23.714286
                      std                 5.962848                 41.019288
                      min                        0                         0
                      max                       19                       197
                      sum                       84                       664
origin_cancelled_rate mean                2.929643                    3.5925
                      std                 6.065335                  6.064061
                      min                      0.0                       0.0
                      max                    22.22                      26.8
                      sum                    82.03                    100.59
dest_cancelled_rate   mean                3.084643                  3.514643
                      std                 6.486163                  6.046634
                      min                      0.0                       0.0
                      max                    22.22                     27.55
                      sum                    86.37                     98.41
avg_dep_delay         mean  0 days 00:20:04.355025    0 days 00:20:02.771529
                      std   0 days 00:15:12.095023    0 days 00:17:27.594401
                      min   0 days 00:04:47.213115    0 days 00:00:16.530612
                      max   0 days 00:50:31.153846    0 days 01:06:03.196721
                      sum   0 days 09:22:01.940702    0 days 09:21:17.602825
avg_arr_delay         mean  0 days 00:13:53.458355    0 days 00:16:45.454399
                      std   0 days 00:21:18.109215    0 days 00:19:58.133279
                      min        -1 days +23:45:15  -1 days +23:54:40.874036
                      max   0 days 01:06:33.191489    0 days 01:04:10.400000
                      sum   0 days 06:28:56.833950    0 days 07:49:12.723176

airport_code                                     EWR  \
total_flights         mean                740.214286
                      std                  41.541908
                      min                        642
                      max                        786
                      sum                      20726
total_cancelled_num   mean                 22.178571
                      std                  44.433099
                      min                          0
                      max                        157
                      sum                        621
origin_cancelled_rate mean                  3.149286
                      std                   6.717769
                      min                        0.0
                      max                      23.84
                      sum                      88.18
dest_cancelled_rate   mean                  3.197857
                      std                     6.4529
                      min                        0.0
                      max                      25.08
                      sum                      89.54
avg_dep_delay         mean    0 days 00:25:00.816465
                      std     0 days 00:22:20.654285
                      min     0 days 00:05:42.724936
                      max     0 days 01:33:39.595142
                      sum     0 days 11:40:22.861030
avg_arr_delay         mean    0 days 00:20:23.763176
                      std     0 days 00:25:34.734885
                      min   -1 days +23:53:36.965944
                      max     0 days 01:37:36.864407
                      sum     0 days 09:31:05.368930

airport_code                                     JFK                       ORD
total_flights         mean                723.321429                   1351.75
                      std                  79.757992                 83.855089
                      min                        503                      1086
                      max                        777                      1432
                      sum                      20253                     37849
total_cancelled_num   mean                 21.428571                 54.892857
                      std                  43.201019                115.108432
                      min                          0                         0
                      max                        175                       457
                      sum                        600                      1537
origin_cancelled_rate mean                  3.361429                  4.031786
                      std                   6.838209                  8.515963
                      min                        0.0                       0.0
                      max                      23.51                     36.07
                      sum                      94.12                    112.89
dest_cancelled_rate   mean                  3.561786                  4.191786
                      std                   7.270686                  8.249917
                      min                        0.0                       0.0
                      max                      26.19                     30.37
                      sum                      99.73                    117.37
avg_dep_delay         mean    0 days 00:21:48.476874    0 days 00:22:23.296720
                      std     0 days 00:19:04.257970    0 days 00:25:50.439790
                      min     0 days 00:01:19.734748    0 days 00:00:47.805596
                      max     0 days 01:18:41.116751    0 days 01:56:05.596529
                      sum     0 days 10:10:37.352479    0 days 10:26:52.308167
avg_arr_delay         mean    0 days 00:18:49.769884    0 days 00:13:22.201774
                      std     0 days 00:21:04.325366    0 days 00:21:27.128753
                      min   -1 days +23:58:12.913386  -1 days +23:53:22.653061
                      max     0 days 01:14:24.193548    0 days 01:16:06.904762
                      sum     0 days 08:47:13.556770    0 days 06:14:21.649673

In [20]:
df.groupby("airport_code")[[
    "avg_temp_c",
    "min_temp_c",
    "max_temp_c",
    "precipitation_mm",
    "max_snow_mm",
    "avg_wind_speed",
    "avg_peakgust"
]].agg(["mean", "std", "min", "max", "sum"]).T

airport_code                 ATL        BOS        EWR        JFK        ORD
avg_temp_c       mean   7.814286   2.557143   3.278571      2.975  -2.260714
                 std    6.541475   4.819284   5.265355   5.203106   6.717602
                 min        -9.6       -7.6      -11.4      -11.6      -19.9
                 max        20.0       11.4       14.2       12.8        4.9
                 sum       218.8       71.6       91.8       83.3      -63.3
min_temp_c       mean   3.896429     -1.225  -1.132143  -0.860714     -5.825
                 std    7.466393   4.491113   5.368913   5.410918   7.654126
                 min       -13.2      -11.6      -13.2      -13.8      -22.1
                 max        16.1        8.9       12.2       12.2        2.8
                 sum       109.1      -34.3      -31.7      -24.1     -163.1
max_temp_c       mean  12.328571   5.971429   7.135714   6.410714   1.142857
                 std     5.80497   5.149819   5.154876   5.174964   6.694576
                 min        -2.7       -6.6       -8.2       -8.8      -18.2
                 max        25.6       15.0       15.6       13.9       11.7
                 sum       345.2      167.2      199.8      179.5       32.0
precipitation_mm mean   3.017857   3.089286      3.875   2.632143   1.964286
                 std    6.235267   7.671416   7.629894   4.882778    6.90653
                 min         0.0        0.0        0.0        0.0        0.0
                 max        21.1       32.5       32.0       17.3       35.1
                 sum        84.5       86.5      108.5       73.7       55.0
max_snow_mm      mean        0.0        NaN        0.0        0.0       0.75
                 std         0.0        NaN        0.0        0.0   1.322876
                 min         0.0        NaN        0.0        0.0        0.0
                 max         0.0        NaN        0.0        0.0        3.0
                 sum         0.0        0.0        0.0        0.0       21.0
avg_wind_speed   mean  13.457143  21.792857  17.678571  22.496429  17.314286
                 std    6.137887   8.062025   6.752852   8.802966   7.420678
                 min         5.0        9.7        6.1        7.6        6.1
                 max        34.2       46.8       34.9       49.0       34.9
                 sum       376.8      610.2      495.0      629.9      484.8
avg_peakgust     mean        NaN        NaN        NaN        NaN        NaN
                 std         NaN        NaN        NaN        NaN        NaN
                 min         NaN        NaN        NaN        NaN        NaN
                 max         NaN        NaN        NaN        NaN        NaN
                 sum           0          0          0          0          0